language: android
android:
  components:
  - extra-google-m2repository
  - extra-android-m2repository
  - platform-tools
  - tools
  - build-tools-25.0.0
  - android-25
jdk:
- oraclejdk8
before_install:
- chmod +x gradlew
- echo 'count=0' > /home/travis/.android/repositories.cfg
install:
  - echo yes | sdkmanager "tools"
  - echo yes | sdkmanager "platforms;android-25" 
  - echo yes | sdkmanager "extras;android;m2repository"
  - echo yes | sdkmanager "extras;google;m2repository"
  - echo yes | sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout;1.0.2"
  - echo yes | sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout-solver;1.0.2"
script: "./gradlew build"
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: oQiiXfrbgBwrVjY4tXious1j/RHiIfqRjSXc8g7HPBgrXKtvRen1tl+fJvuAcsmyVtXzCa7ALls2il5Tps6qNTpHATwT9LT5VcycXQWOC5v6xmYeOjud285yOEjl8tjWYure/DFCKAuun4r15YkY9P0LDlhHOhzqp3fOphRi8iG6ds+b8zlM77JW3aZGjwlaJoXBwlki+aSKaRiSPn3FDgddhwYiME6P9yngvwKOJHXLBB6t/Ht/ZEvE79YBvCBCmCgqHVcG9frbS71o91X/3jSRbYbPJmUkWoznrXjira8Zuy6sPxJBwTrZrhUFyakIFSzAKAT6iGlQKEUHRD+MTa/M7AHXo6AM/XZfGGcEG2kX6xTyexUkCYY7xDd9Rk0XTmXHzMPLMBPhybgLE4zUKpjyFeDeetHsq9fWzNtpylVgEyeGWlHrYfYz3qZBuLGnjseliZh0SDnskErvOcSxLW4frAdD6XVzKj1jujMhI+Dl4B+DKEZZu4FvBg32GyMl9gz7OTubYiNfcmeFdfJqnxfAzNiRCxVB/lLdyi+lMkuxiyHCi5mxqKBhM392ZTO7IJbC6gBSngwEqmx38Thin3FnjpOA2Y0aj7mvILrY45EJlnqJMIiE9tsu39l0bPli36nDqFdnQIdTSbD9lmfDSc2wmVcPlhxk5Kjp00g+uqs=
  file: app/build/outputs/apk/app-debug.apk
  file_glob: "true"
  on:
    repo: berkantkz/KLU_Yemek
