name: Node CI

on: 
    push:
        branches:
            - master
    schedule: 
        - cron: '0 */6 * * *'

jobs:
  build:

    runs-on: ubuntu-18.04

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: navigate listgen
      run: cd listgen
    - name: npm i
      run: npm i
    - name: node index.js
      run: node index.js
    - name: deploy
      run: cd .. & ./deploy.sh
      env:
        CI: true
        ACCESS_TOKEN: ${{ secrets.token }}
        BASE_BRANCH: master
        BRANCH: master
       
