name: Main workflow
on: push
jobs:
  run:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        node-version: [8.x, 10.x]
    steps:
    - uses: actions/checkout@v1
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install
      run: npm install
      
    - name: node index.js
      run: node index.js
    
    - name: git push
      run: git add list.json && git commit -am 'update list' && git push -f
      
      env:
        CI: true
